/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.datatablescenarioswmo.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class HqlCustomVacationDataResponse implements Serializable {


    @ColumnAlias("EMPID")
    private Integer empid;

    @ColumnAlias("VTYPE")
    private String vtype;

    @ColumnAlias("VSTATUS")
    private String vstatus;

    @ColumnAlias("VSTARTDATE")
    private Date vstartdate;

    @ColumnAlias("VENDDATE")
    private Date venddate;

    public Integer getEmpid() {
        return this.empid;
    }

    public void setEmpid(Integer empid) {
        this.empid = empid;
    }

    public String getVtype() {
        return this.vtype;
    }

    public void setVtype(String vtype) {
        this.vtype = vtype;
    }

    public String getVstatus() {
        return this.vstatus;
    }

    public void setVstatus(String vstatus) {
        this.vstatus = vstatus;
    }

    public Date getVstartdate() {
        return this.vstartdate;
    }

    public void setVstartdate(Date vstartdate) {
        this.vstartdate = vstartdate;
    }

    public Date getVenddate() {
        return this.venddate;
    }

    public void setVenddate(Date venddate) {
        this.venddate = venddate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof HqlCustomVacationDataResponse)) return false;
        final HqlCustomVacationDataResponse hqlCustomVacationDataResponse = (HqlCustomVacationDataResponse) o;
        return Objects.equals(getEmpid(), hqlCustomVacationDataResponse.getEmpid()) &&
                Objects.equals(getVtype(), hqlCustomVacationDataResponse.getVtype()) &&
                Objects.equals(getVstatus(), hqlCustomVacationDataResponse.getVstatus()) &&
                Objects.equals(getVstartdate(), hqlCustomVacationDataResponse.getVstartdate()) &&
                Objects.equals(getVenddate(), hqlCustomVacationDataResponse.getVenddate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmpid(),
                getVtype(),
                getVstatus(),
                getVstartdate(),
                getVenddate());
    }
}