/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.datatablescenarioswmo.dbscenarios.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SvUpdateListOfRecordsRequest implements Serializable {


    @JsonProperty("UROLE")
    @NotNull
    private String urole;

    @JsonProperty("USERID")
    @NotNull
    private List<Integer> userid;

    public String getUrole() {
        return this.urole;
    }

    public void setUrole(String urole) {
        this.urole = urole;
    }

    public List<Integer> getUserid() {
        return this.userid;
    }

    public void setUserid(List<Integer> userid) {
        this.userid = userid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvUpdateListOfRecordsRequest)) return false;
        final SvUpdateListOfRecordsRequest svUpdateListOfRecordsRequest = (SvUpdateListOfRecordsRequest) o;
        return Objects.equals(getUrole(), svUpdateListOfRecordsRequest.getUrole()) &&
                Objects.equals(getUserid(), svUpdateListOfRecordsRequest.getUserid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getUrole(),
                getUserid());
    }
}